// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: cars.queries.sql

package models

import (
	"context"
)

const findAllCars = `-- name: FindAllCars :many
SELECT id, brand, model, year, price FROM cars
`

func (q *Queries) FindAllCars(ctx context.Context) ([]Car, error) {
	rows, err := q.query(ctx, q.findAllCarsStmt, findAllCars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Car
	for rows.Next() {
		var i Car
		if err := rows.Scan(
			&i.ID,
			&i.Brand,
			&i.Model,
			&i.Year,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCar = `-- name: InsertCar :one
INSERT INTO cars (brand, model, year, price) VALUES (?, ?, ?, ?) RETURNING id, brand, model, year, price
`

type InsertCarParams struct {
	Brand string  `json:"brand"`
	Model string  `json:"model"`
	Year  int64   `json:"year"`
	Price float64 `json:"price"`
}

func (q *Queries) InsertCar(ctx context.Context, arg InsertCarParams) (Car, error) {
	row := q.queryRow(ctx, q.insertCarStmt, insertCar,
		arg.Brand,
		arg.Model,
		arg.Year,
		arg.Price,
	)
	var i Car
	err := row.Scan(
		&i.ID,
		&i.Brand,
		&i.Model,
		&i.Year,
		&i.Price,
	)
	return i, err
}
