// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

type Car struct {
	ID    int64   `json:"id"`
	Brand string  `json:"brand"`
	Model string  `json:"model"`
	Year  int64   `json:"year"`
	Price float64 `json:"price"`
}
