// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"context"
)

type Querier interface {
	FindAllCars(ctx context.Context) ([]Car, error)
	InsertCar(ctx context.Context, arg InsertCarParams) (Car, error)
}

var _ Querier = (*Queries)(nil)
